name: Build/release

on:
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
          
      - name: Install electron rebuilder
        run: npm install --save-dev @electron/rebuild
        working-directory: ./app
          
      - name: Run the electron rebuilder
        run: ./node_modules/.bin/electron-rebuild
        working-directory: ./app
        
      - name: Install npm packages
        run: npm install
        working-directory: ./app
        
      - name: Postinstall npm packages
        run: npm run postinstall
        working-directory: ./app
      
      - name: build application mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        working-directory: ./app
              
      - name: build application win
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        working-directory: ./app
        
      - name: archive artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: app/dist/*.exe
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: download artifacts
        uses: actions/download-artifact@master
        with:
          name: dist
          path: artifacts
    
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "/home/runner/work/keasy/keasy/artifacts/*"

        

              


