name: Build/release

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
          
      - name: Install electron rebuilder
        run: npm install --save-dev @electron/rebuild
        working-directory: ./app
          
      - name: Run the electron rebuilder
        run: ./node_modules/.bin/electron-rebuild
        working-directory: ./app
        
      - name: Install npm packages
        run: npm install
        working-directory: ./app
        
      - name: Postinstall npm packages
        run: npm run postinstall
        working-directory: ./app
      
      - name: build application mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        working-directory: ./app
              
      - name: build application win
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        working-directory: ./app
        
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            app/dist/*.dmg
            app/dist/*mac.zip
            app/dist/*.exe
            
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist"

        

              


